import type { ChecklistStage, ItemStatus } from "./types";

const g = (
  id: string,
  title: string,
  items: Array<string | [string, boolean]>,
  defaultStatus: ItemStatus = "pendente",
) => ({
  id,
  title,
  items: items.map((it) => {
    const [label, critical] = Array.isArray(it) ? it : [it, false];
    return {
      id: `${id}__${label.toLowerCase().replace(/[^a-z0-9]+/g, "_").slice(0, 60)}`,
      label,
      critical,
      status: defaultStatus,
    };
  }),
});

export const CHECKLIST_TEMPLATE: ChecklistStage[] = [
  {
    id: "comercial",
    title: "Etapa Comercial",
    description: "Definição de parceria, contrapartidas e contrato.",
    groups: [
      g("comercial_parceria", "Definição da parceria", [
        "Patrocínio Ouro",
        "Patrocínio Prata",
        "Patrocínio Bronze",
        "Apoio",
        "Fornecedor Oficial de Internet",
        "Venda de internet temporária",
        "Permuta",
        ["Contrato financeiro", true],
      ]),
      g(
        "comercial_contrapartidas",
        "Contrapartidas negociadas",
        [
          "Logo em banner",
          "Logo em painel",
          "Logo em telão",
          "Logo em backdrop",
          "Logo em ingressos",
          "Logo em pulseiras",
          "Logo em credenciais",
          "Logo no site",
          "Logo nas redes sociais",
          "Marcação nas publicações",
          "Stories",
          "Reels",
          "Vídeo institucional",
          "Citação pelo locutor",
          "Espaço para ativação",
          "Espaço para stand",
          "Espaço para venda",
          "Exclusividade como internet oficial",
        ],
        "na",
      ),
    ],
  },
  {
    id: "tecnico",
    title: "Levantamento Técnico",
    description: "Vistoria, definição de local e infraestrutura necessária.",
    groups: [
      g("tec_local", "Local e infraestrutura", [
        ["Endereço confirmado", true],
        ["Visita técnica realizada", true],
        "Definição do local do stand pelo marketing",
        "Definição do local dos equipamentos pela equipe técnica",
        ["Ponto de energia disponível", true],
        "Local protegido para equipamentos",
        "Necessidades levantadas",
        "Local para guardar itens do evento depois que acabar",
      ]),
      g("tec_internet", "Necessidade de internet", [
        "Bilheteria",
        "Caixa",
        "Máquinas de cartão",
        "Credenciamento",
        "Transmissão ao vivo",
        "Equipamento cabeado (informar quais nas observações)",
        "Imprensa",
        "Camarim",
        "Produção",
        "Segurança",
        "Staff",
        "Expositores",
        "Público",
        "Streaming",
        "Monitoramento por câmeras",
      ]),
      g("tec_banda", "Banda necessária", [
        "Até 100 Mbps",
        "300 Mbps",
        "500 Mbps",
        "700 Mbps",
        "1 Gbps",
        ["Link dedicado", true],
        "Link redundante",
      ]),
    ],
  },
  {
    id: "instalacao",
    title: "Instalação",
    description: "Agendamento, equipe, materiais e testes pré-evento.",
    groups: [
      g("inst_geral", "Preparação e instalação", [
        ["Data agendada", true],
        ["Equipe de trabalho definida", true],
        "Veículo disponível",
        "Materiais conferidos",
        "Equipamentos configurados",
        ["Teste de internet realizado com responsável (5h antes)", true],
        "Instalação de tenda, balão, balcão ou outros itens",
        "Fotos da instalação",
        ["Assinatura do responsável", true],
      ]),
    ],
  },
  {
    id: "operacao",
    title: "Operação durante o evento",
    description: "Presença técnica, marketing, materiais, equipe e registros.",
    groups: [
      g("op_geral", "Operação técnica", [
        ["Técnico de plantão", true],
        ["Canal direto com produção", true],
      ]),
      g("op_stand", "Ações de marketing — Stand", [
        "Wind Banner",
        "Balcão",
        "Totem",
        "Roleta",
        "Tablet",
        "Cadeiras",
        "Tenda",
        "Iluminação",
        "Extensão",
        "Balão",
      ]),
      g("op_materiais", "Materiais", [
        "Panfletos",
        "Flyers",
        "QR Codes",
        "Brindes",
        "Camisas de trabalho",
      ]),
      g("op_equipe", "Equipe", [
        "Supervisor",
        "Comercial",
        "Marketing",
        "Técnico",
        "Atendimento",
        "Fotógrafo",
        "Apoio",
      ]),
      g("op_registros", "Registros", [
        "Fotos do stand",
        "Fotos da equipe",
        "Fotos dos clientes",
        "Vídeos",
        "Depoimentos",
        "Bastidores",
        "Reels gravados",
        "Stories publicados",
      ]),
    ],
  },
  {
    id: "pos",
    title: "Pós-evento",
    description: "Encerramento, conferência e aprendizados.",
    groups: [
      g("pos_geral", "Fechamento", [
        ["Retirada dos equipamentos", true],
        "Conferência dos materiais",
        "Devolução de itens de evento e brindes ao estoque",
        "Oportunidades de melhoria",
        "Arquivamento de fotos e documentos",
      ]),
    ],
  },
];
