/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsIdReportRouteImport } from './routes/events.$id.report'
import { Route as EventsIdChecklistRouteImport } from './routes/events.$id.checklist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdReportRoute = EventsIdReportRouteImport.update({
  id: '/events/$id/report',
  path: '/events/$id/report',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdChecklistRoute = EventsIdChecklistRouteImport.update({
  id: '/events/$id/checklist',
  path: '/events/$id/checklist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/new': typeof EventsNewRoute
  '/events/$id/checklist': typeof EventsIdChecklistRoute
  '/events/$id/report': typeof EventsIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/new': typeof EventsNewRoute
  '/events/$id/checklist': typeof EventsIdChecklistRoute
  '/events/$id/report': typeof EventsIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/new': typeof EventsNewRoute
  '/events/$id/checklist': typeof EventsIdChecklistRoute
  '/events/$id/report': typeof EventsIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/events/new' | '/events/$id/checklist' | '/events/$id/report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events/new' | '/events/$id/checklist' | '/events/$id/report'
  id:
    | '__root__'
    | '/'
    | '/events/new'
    | '/events/$id/checklist'
    | '/events/$id/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsNewRoute: typeof EventsNewRoute
  EventsIdChecklistRoute: typeof EventsIdChecklistRoute
  EventsIdReportRoute: typeof EventsIdReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/report': {
      id: '/events/$id/report'
      path: '/events/$id/report'
      fullPath: '/events/$id/report'
      preLoaderRoute: typeof EventsIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/checklist': {
      id: '/events/$id/checklist'
      path: '/events/$id/checklist'
      fullPath: '/events/$id/checklist'
      preLoaderRoute: typeof EventsIdChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsNewRoute: EventsNewRoute,
  EventsIdChecklistRoute: EventsIdChecklistRoute,
  EventsIdReportRoute: EventsIdReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
